Repository Arkhist/Hacknet-Pathfinder, pull requests merged in 2022-07, with the labels that each got.

#181 Fix #168 Generated nodes missing ports again
  PathfinderAPI/Replacements/ReplacementsCommon.cs
Labels: Bug

#176 Add support for TextRecord and OnlineAccount as Data Types in Database Daemon
  PathfinderAPI/Replacements/ObjectSerializerReplacement.cs
Labels: Enhancement

#156 Fix #152
  PathfinderAPI/Executable/ExecutableManager.cs
Labels: Bug, Enhancement
